1.Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.



In [100]:
import numpy as np
import time

1.1

In [143]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
# X  = np.random.rand(100,100)
def func(X):
    X_1 = np.diag(X)
    X_1 = X_1[X_1!=0]
    return np.prod(X_1[X_1!=0])
print(func(X))
%timeit func(X)


3
12.7 µs ± 2.24 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


1.2


In [142]:
def func(X):
    n=min(X.shape[0],X.shape[1])
    X_copy= np.hstack(X[0:n,0:n])
    mult=1
    i=0
    for count in range(n):
        if(X_copy[i]!=0):
            mult*=X_copy[i]
        i=i+n+1
    return mult
# X  = np.random.rand(100,100)
print(func(X))
%timeit func(X)

1.2273439251379158e-45
146 µs ± 26.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


1.3

In [122]:
def func(X):
    mult=1
    n=min(X.shape[0],X.shape[1])
    for i in range(n):
        if X[i][i]!=0:
            mult*=X[i][i]
    return mult
# X  = np.random.rand(100,100)
print(func(X))
%timeit func(X)

3
3.2 µs ± 973 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


2.  Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.

2.1

In [146]:
def func(x,y):
    x=set(x)
    y=set(y)
    if x!=y:
        return False
    else:
        return True


x = np.array([4, 2, 2, 1])
y = np.array([4, 2, 1, 2])
# x = np.random.rand(1000)
# y = np.random.rand(1000)
print(func(x,y))
%timeit func(x,y)

True
2.71 µs ± 54.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


2.2

In [126]:
def func(x,y):
    x=np.unique(x)
    y=np.unique(y)
    if(len(x)!=len(y)):
        return False
    elif(np.all(x==y)):
        return True
    else:
        return False

x = np.array([4, 2, 2, 1])
y = np.array([4, 2, 1, 2])
# x = np.random.rand(1000)
# y = np.random.rand(1000)
print(func(x,y))
%timeit func(x,y)

True
21.5 µs ± 2.89 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


2.3

In [127]:
def func(x,y):

    x.sort()
    y.sort()
    if sum(x%y)==0:
        return True
    else:
        return False
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
# x = np.random.rand(1000)
# y = np.random.rand(1000)
print(func(x,y))
%timeit func(x,y)

True
3.62 µs ± 219 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


2.4

In [128]:
def func(x,y):
    ind=0
    x.sort()
    y.sort()
    for i in range(len(x)):
        if x[i]!=y[i]:
            return False
    return True
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
# x = np.random.rand(1000)
# y = np.random.rand(1000)
print(func(x,y))
%timeit func(x,y)

True
2.13 µs ± 65.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


3. Найти максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой.

3.1

In [129]:
def func(X):
    a=[]
    for i in range(len(X)):
        if X[i]==0 and i!=len(X)-1:
            a.append(X[i+1])
    X=np.array([a])
    return np.max(X)
X = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
#X=np.random.rand(1000)
print(func(X))
%timeit func(X)

5
11.9 µs ± 5.97 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


3.2

In [131]:
def func(X):
    mask = X[:-1] == 0
    max_element = np.max(X[1:][mask])
    return max_element

X = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
#X=np.random.rand(1000)
print(func(X))
%timeit func(X)

5
6.81 µs ± 161 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


3.3

In [132]:
def func(X):
  return max((X[i] for i in range(1, len(X)) if X[i - 1] == 0))
X = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
#X=np.random.rand(1000)
print(func(X))
%timeit func(X)

5
2.65 µs ± 35.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


4. Дан трёхмерный массив, содержащий изображение, размера (height, width, numChannels), а также вектор длины numChannels. Сложить каналы изображения с указанными весами, и вернуть результат в виде матрицы размера (height, width). Считать реальное изображение можно при помощи функции scipy.misc.imread (если изображение не в формате png, установите пакет pillow: conda install pillow). Преобразуйте цветное изображение в оттенки серого, использовав коэффициенты np.array([0.299, 0.587, 0.114]).


4.1

In [133]:
import imageio.v2 as imageio

def func(a,weights):
    for i in range(a.shape[2]):
        if i == 0:
            for j in range(a.shape[0]):
                for k in range(a.shape[1]):
                    a[j][k][i]=weights[i]*a[j][k][i]
        else:
            for j in range(a.shape[0]):
                for k in range(a.shape[1]):
                    a[j][k][0]+=weights[i]*a[j][k][i]
    return a[:,:,0]
im = imageio.imread('pic1.png')
Im = np.asarray(im)
weights = np.array([0.299, 0.587, 0.114])
print(func(Im,weights))
imageio.imwrite('pic2.png',func(Im,weights))
%timeit func(Im,weights)



[[117 118 118 ...  44  47  47]
 [117 118 118 ...  46  46  46]
 [117 118 118 ...  46  46  44]
 ...
 [134 136 137 ...  46  47  50]
 [136 137 137 ...  44  46  48]
 [136 137 138 ...  46  46  48]]
4.58 s ± 639 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


4.2

In [134]:
def func(im_1,w):
  im_1 = np.dot(np.reshape(im_1,(-1,im_1.shape[1],im_1.shape[2])),w)
  #print(im_1)
  return im_1
im = imageio.imread('pic1.png')
Im = np.asarray(im)
weights = np.array([0.299, 0.587, 0.114])
print(func(Im,weights).shape)
imageio.imwrite('pic21.png',func(Im,weights).astype(np.uint8))
%timeit func(Im,weights)

(720, 1280)
38 ms ± 10.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


4.3

In [135]:
def func(im,w):
    image = np.zeros((im.shape[0],im.shape[1]))
    for i in range(im.shape[2]):
        image+=im[:,:,i]*w[i]
    return image

im = imageio.imread('pic1.png')
Im = np.asarray(im)
weights = np.array([0.299, 0.587, 0.114])
print(func(Im,weights).shape)
imageio.imwrite('pic22.png',func(Im,weights).astype(np.uint8))
%timeit func(Im,weights)

(720, 1280)
6.69 ms ± 1.52 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


5.Реализовать кодирование длин серий (Run-length encoding). Дан вектор x. Необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.

5.1


In [136]:
def func(x):
    val = []
    kol = []
    val.append(x[0])
    kol.append(1)
    j=0
    for i in range(1,len(x),1):
        if(val[j]==x[i]):
            kol[j]+=1
        else:
            j+=1
            val.append(x[i])
            kol.append(1)
    return val, kol
x = np.array([2, 2, 2, 3, 3, 3, 5, 2, 2])
#x=np.random.rand(1000)

print(func(x))
%timeit func(x)

([2, 3, 5, 2], [3, 3, 1, 2])
3.04 µs ± 54.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


5.2

In [137]:
def func(x):
    btw = (x[1:] != x[:-1])
    y = np.append(np.where(btw), len(x)-1)
    parts = np.split(x, y+1)
    values, counts=np.zeros(len(parts)-1),np.zeros(len(parts)-1)
    for i in range(len(parts)-1):
        values[i]=parts[i][0]
        counts[i]=len(parts[i])
    return (values, counts)
x = np.array([2, 2, 2, 3, 3, 3, 5, 2, 2])
#x=np.random.rand(1000)
print(func(x))
%timeit func(x)

(array([2., 3., 5., 2.]), array([3., 3., 1., 2.]))
48.4 µs ± 13.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


5.3

In [138]:
def func(x):
    indices = np.concatenate(([0], np.where(np.diff(x) != 0)[0] + 1, [len(x)]))
    numbers = x[indices[:-1]]
    counts = np.diff(indices)
    return numbers, counts

x = np.array([2, 2, 2, 3, 3, 3, 5, 2, 2])
#x=np.random.rand(1000)
print(func(x))
%timeit func(x)



(array([2, 3, 5, 2]), array([3, 3, 1, 2]))
19.6 µs ± 5.19 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Вывод: при работе с небольшим количеством данных циклические методы даже решают задачи быстрее тех, в которых используется numpy. Но с ростом (особенно после 1000 элементных массивов или матриц) numpy уверенно обыгрывет по скорости работы программы, написанные с помощью for, while и тп.